//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taq22100900058_lession11.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TaqK22CNTt3Lession11DbEntities : DbContext
    {
        public TaqK22CNTt3Lession11DbEntities()
            : base("name=TaqK22CNTt3Lession11DbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TaqCategory> TaqCategories { get; set; }
        public virtual DbSet<TaqProduct> TaqProducts { get; set; }
    }
}
