//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taq22100900058_lession11.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Xml.Linq;

    public partial class TaqCategory
    {
        [Display(name = "ma danh muc ")]
        public int TaqID { get; set; }
        [Display(name = "ten danh muc ")]
        public string TaqCateName { get; set; }
        [Display(name = "trang thai  ")]
        public Nullable<int> TaqStatus { get; set; }
    }
}
