//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taq22100900058_lession11.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaqProduct
    {
        public string TaqID2210900058 { get; set; }
        public string TaqProName { get; set; }
        public Nullable<int> TaqQty { get; set; }
        public Nullable<double> TaqPrice { get; set; }
        public Nullable<int> TaqCateID { get; set; }
        public Nullable<bool> TaqActive { get; set; }
    }
}
